In [ ]:
!pip install -q spacy

In [ ]:
!pip install -U spacy[cuda]
!nvcc --version
!python -m spacy download en_core_web_sm

Requirement already satisfied: spacy[cuda] in /usr/local/lib/python3.11/dist-packages (3.8.6)
Collecting spacy[cuda]
  Downloading spacy-3.8.7-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (3.0.9)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (0.15.3)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (2.11.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (24.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from spacy[cuda]) (3.5.0)
Collecting cupy<13.0.0,>=5.0.0b4 (from spacy[cuda])
  Downloading cupy-12.3.0.tar.gz (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 33.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy>=1.19.0 (from spacy[cuda])
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.1 MB/s eta 0:00:00
Requirement already satisfied: fastrlock>=0.5 in /usr/local/lib/python3.11/dist-packages (from cupy<13.0.0,>=5.0.0b4->spacy[cuda]) (0.8.3)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.11/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy[cuda]) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[cuda]) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[cuda]) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[cuda]) (4.13.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[cuda]) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy[cuda]) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy[cuda]) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy[cuda]) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy[cuda]) (2025.4.26)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from thinc<8.4.0,>=8.3.4->spacy[cuda]) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from thinc<8.4.0,>=8.3.4->spacy[cuda]) (0.1.5)
INFO: pip is looking at multiple versions of thinc to determine which version is compatible with other requirements. This could take a while.
Collecting thinc<8.4.0,>=8.3.4 (from spacy[cuda])
  Downloading thinc-8.3.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Collecting blis<1.3.0,>=1.2.0 (from thinc<8.4.0,>=8.3.4->spacy[cuda])
  Downloading blis-1.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy[cuda]) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy[cuda]) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy[cuda]) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy[cuda]) (0.21.1)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy[cuda]) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->spacy[cuda]) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy[cuda]) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy[cuda]) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy[cuda]) (2.19.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy[cuda]) (1.17.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy[cuda]) (0.1.2)
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 58.1 MB/s eta 0:00:00
Downloading thinc-8.3.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 41.3 MB/s eta 0:00:00
Downloading spacy-3.8.7-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.0/33.0 MB 15.3 MB/s eta 0:00:00
Downloading blis-1.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 29.2 MB/s eta 0:00:00
Building wheels for collected packages: cupy
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for cupy (setup.py) ... error
  ERROR: Failed building wheel for cupy
  Running setup.py clean for cupy
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for cupy
Failed to build cupy
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cupy)
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 115.5 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("jigsaw-toxic-comment-train.csv", on_bad_lines='skip',engine='python')
df.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223549 entries, 0 to 223548
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             223549 non-null  object
 1   comment_text   223549 non-null  object
 2   toxic          223549 non-null  int64
 3   severe_toxic   223549 non-null  int64
 4   obscene        223549 non-null  int64
 5   threat         223549 non-null  int64
 6   insult         223549 non-null  int64
 7   identity_hate  223549 non-null  int64
dtypes: int64(6), object(2)
memory usage: 13.6+ MB

In [ ]:
df = df.drop(columns = ['id'])

In [ ]:
one_hot_cols = ['toxic','severe_toxic','obscene','threat','insult','identity_hate']

In [ ]:
df['category'] = df[one_hot_cols].idxmax(axis=1)

In [ ]:
df.head()

,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,category
0,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0,toxic
1,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0,toxic
2,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0,toxic
3,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0,toxic
4,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0,toxic

In [ ]:
df = df.drop(columns = one_hot_cols)

In [ ]:
df

                                             comment_text category
0       Explanation\nWhy the edits made under my usern...    toxic
1       D'aww! He matches this background colour I'm s...    toxic
2       Hey man, I'm really not trying to edit war. It...    toxic
3       "\nMore\nI can't make any real suggestions on ...    toxic
4       You, sir, are my hero. Any chance you remember...    toxic
...                                                   ...      ...
223544  :Jerome, I see you never got around to this…! ...    toxic
223545  ==Lucky bastard== \n http://wikimediafoundatio...    toxic
223546  ==shame on you all!!!== \n\n You want to speak...    toxic
223547  MEL GIBSON IS A NAZI BITCH WHO MAKES SHITTY MO...    toxic
223548  " \n\n == Unicorn lair discovery == \n\n Suppo...    toxic

[223549 rows x 2 columns]

Text Preprocessing

In [ ]:
import spacy
import re
nlp = spacy.load("en_core_web_sm", disable=["ner", "parser"])  # Faster by disabling unneeded components
spacy.require_gpu()
# Set of stopwords
stopwords = nlp.Defaults.stop_words

# Simple regex stemmer
stemmer = re.compile(r'(ing$|ed$|s$)')

In [ ]:
def batch_process_spacy(texts):
    results = []
    for doc in nlp.pipe(texts, batch_size=1000, n_process=2):  # Adjust batch and process count
        tokens = [
            stemmer.sub('', token.text.lower())
            for token in doc
            if token.text.lower() not in stopwords and token.is_alpha
        ]
        results.append(" ".join(tokens))
    return results

df['cleaned_comment'] = batch_process_spacy(df['comment_text'].tolist())

In [ ]:
df['cleaned_comment']

0         explanation edit username hardcore metallica f...
1         matche background colour seemingly stuck thank...
2         hey man try edit war guy constantly remov rele...
3         real suggestion improvement wonder section sta...
4                             sir hero chance remember page
                                ...
223544    jerome got surpris look example nomine plainso...
223545                    lucky heh famou kida envy congrat
223546                        shame want speak gay romanian
223547    mel gibson nazi bitch make shitty movie buttse...
223548    unicorn lair discovery supposedly unicorn lair...
Name: cleaned_comment, Length: 223549, dtype: object

In [ ]:
df['cleaned_comment'][6]

'cocksucker pis work'

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
df= df[df['cleaned_comment'].notnull() & (df['cleaned_comment'].str.strip() != '')].reset_index(drop=True)


comments = df['cleaned_comment'].astype(str).tolist()

In [ ]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(comments)
print(f'TF_IDF matrix shape:{tfidf_matrix.shape}')

TF_IDF matrix shape:(223113, 200169)

In [ ]:
from sklearn.decomposition import TruncatedSVD
n_components = 300
svd = TruncatedSVD(n_components=n_components, random_state = 42)
X_reduced = svd.fit_transform(tfidf_matrix)
print(f'After TruncatedSVD,shape :{X_reduced.shape}')

After TruncatedSVD,shape :(223113, 300)

In [ ]:
X_reduced

array([[ 0.15251048,  0.07827054,  0.03897989, ..., -0.0217508 ,
         0.00217676,  0.01218584],
       [ 0.09052287, -0.01230342,  0.1160824 , ..., -0.0027929 ,
        -0.00252753, -0.00283263],
       [ 0.26360956,  0.13708327,  0.02451747, ..., -0.01850448,
        -0.01017487, -0.0088083 ],
       ...,
       [ 0.19076441, -0.07172017,  0.05290423, ..., -0.00058804,
        -0.0240464 , -0.00102167],
       [ 0.01562909, -0.00786032, -0.01398281, ...,  0.00031296,
        -0.03079122,  0.00647125],
       [ 0.05152646, -0.02390117, -0.02763271, ...,  0.00587911,
         0.00960474,  0.00335821]])

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['category'] = encoder.fit_transform(df['category'])
len(df['category'])

223113

In [ ]:
np.savez_compressed('hate_comments_reduced.npz', X=X_reduced, y=df['category'])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!mv /content/hate_comments_reduced.npz /content/drive/MyDrive/hate_comments_reduced.npz